### ISSUE TITLE
How search for 

### ISSUE THREAD

**Issue by warchiefmarkus** [Gaolious/analysis-township#3]
Hello, sorry but can you explain or add info to Readme how you find this two constants to calculate file size ? 

size = (pHeader->hash_length - ((pSrcXML->capacity + 8) ^ **0xC5EEDu**)) ^ **0x396A8u**;

All code are understandable but this two constant is come from nowhere.

**Comment by Gaolious** [comment]
I understand that the two constants might be used for obfuscation, security, or as magic numbers, but I’m not sure why these specific constants were chosen. I found them while reverse-engineering a library file using IDA.

**Comment by warchiefmarkus** [comment]
Thank you very much !🙏
